---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        args: ['--line-length=100']
        files: ^(utils/|tests/|.*\.py$)

  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: ['--profile=black', '--line-length=100']
        files: ^(utils/|tests/|.*\.py$)

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args:
          - '--max-line-length=100'
          - '--extend-ignore=E203,W503'
          - '--per-file-ignores=__init__.py:F401'
        files: ^(utils/|tests/)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args: ['--config-file=pyproject.toml']
        files: ^utils/
        additional_dependencies:
          - pandas-stubs
          - types-requests
          - pandas
          - numpy
          - supabase
